spring:
  application:
    name:
      gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/user/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
          '[/refreshToken]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
          '[/auth/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
          '[/login]':
            allowedOrigins: "*"
            allowedMethods:
              - POST
          '[/inventory/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST

server:
  port: 8888
